name = "boss-vao-lenh"
main = "src/index.js"
compatibility_date = "2026-09-25"

[triggers]
crons = ["*/5 * * * *"]

[[kv_namespaces]]
binding = "BOSS_KV"
id = "843ba5a3a1cf434da559ea21e59d87c7"

# PREDICT_API_KEY is configured as a Cloudflare runtime secret.
